INSERT INTO INSTRUMENT_PRICE_MODIFIER (ID, NAME, VALUE) VALUES (1, 'INSTRUMENT1', 1.09);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (ID, NAME, VALUE) VALUES (2, 'INSTRUMENT2', 1.87);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (ID, NAME, VALUE) VALUES (3, 'INSTRUMENT3', 1.12);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (ID, NAME, VALUE) VALUES (4, 'INSTRUMENT5', 1.10);